# Generated by Django 5.0.6 on 2024-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
    ]
