# Generated by Django 5.0.6 on 2024-06-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_expert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Эксперт', 'verbose_name_plural': 'Эксперты'},
        ),
    ]
