# Generated by Django 5.0.6 on 2024-06-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_settings_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Обо мне', 'verbose_name_plural': 'Обо мне'},
        ),
    ]
