# Generated by Django 5.0.6 on 2024-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_settings_facebook_settings_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название награды')),
                ('year', models.DateField(verbose_name='Год получения')),
            ],
        ),
    ]
