# Generated by Django 5.0.6 on 2024-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rewards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewards',
            options={'verbose_name': 'Награда', 'verbose_name_plural': 'Награды'},
        ),
        migrations.AlterField(
            model_name='rewards',
            name='year',
            field=models.IntegerField(verbose_name='Год получения'),
        ),
    ]
