# Generated by Django 5.0.6 on 2024-06-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название работы')),
                ('published', models.IntegerField(verbose_name='Опубликовано')),
                ('description', models.TextField(verbose_name='Описание работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='EducationInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название профессии')),
                ('description', models.TextField(verbose_name='Место обучение и год')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_inline', to='base.positions')),
            ],
            options={
                'unique_together': {('education', 'title', 'description')},
            },
        ),
    ]
