# Generated by Django 5.0.6 on 2024-06-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_works_educationinline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='published',
            field=models.DateField(verbose_name='Опубликовано'),
        ),
    ]
