# Generated by Django 5.0.6 on 2024-06-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_experience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationInline',
            new_name='Education',
        ),
    ]
