# Generated by Django 5.0.6 on 2024-06-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_educationinline_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterUniqueTogether(
            name='education',
            unique_together=set(),
        ),
    ]
