# Generated by Django 5.0.6 on 2024-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('created', models.DateField(verbose_name='Дата создания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
