# Generated by Django 5.0.6 on 2024-06-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Последний блог', 'verbose_name_plural': 'Последние блоги'},
        ),
    ]
